### ISSUE TITLE
[ng] Forms guide - validation classes

### ISSUE THREAD

**Issue by Janamou** [dart-lang/site-webdev#333] opened 2017-01-25 13:52 UTC
Hi,

the forms guide (https://webdev.dartlang.org/angular/guide/forms#!#add-custom-css-for-visual-feedback) mentions validation classes - e.g. `ng-untouched ng-valid ng-pristine` etc. My problem is that they just don't appear to me, even when I copy paste the sample:

```dart
<input type="text" class="form-control" required
       [(ngModel)]="model.name"
       ngControl="name" #spy >
TODO: remove this: {{spy.className}}
```

The example doesn't have them too: http://angular-examples.github.io/forms/

Compare with Typescript docs: https://angular.io/docs/ts/latest/guide/forms.html and the first example, which has them: https://angular.io/resources/live-examples/forms/ts/eplnkr.html

**Are these validation classes supported in Dart?**

**Comment by chalin** [comment] 2017-01-25 15:28
Hi Jana. Thanks for the feedback.

These classes are no longer being set automatically (the class responsible for it, `NgControlStatus`, has been deprecated).

Btw, if you are working through the forms chapter, you might want to wait a little since I'm working on a revision, which will address this issue and more.

I'm closing this for now since the issue is being covered by #114.

**Closed by chalin** 2017-01-25 15:28 UTC
Labels: Angular

**Comment by Janamou** [comment] 2017-01-25 16:38
@chalin ok, thank you and looking forward to the updated docs! :-)
